from __future__ import annotations

from app.schemas import (
    Ambulance,
    CapacityStatus,
    Hospital,
    Location,
    PatientRecord,
    SpecialistRoster,
)


def seed_hospitals() -> dict[str, Hospital]:
    hospitals = [
        Hospital(
            id="korle-bu-teaching",
            name="Korle Bu Teaching Hospital",
            city="Accra",
            level="teaching",
            location=Location(city="Accra", latitude=5.5363, longitude=-0.2275, address="Guggisberg Avenue"),
            capabilities=["icu", "oxygen", "ct", "trauma", "stroke", "surgical_team", "ventilator", "blood_bank"],
            capacity=CapacityStatus(
                er_beds_available=3,
                icu_beds_available=2,
                maternity_beds_available=2,
                pediatric_beds_available=2,
                isolation_rooms_available=1,
                oxygen_points_available=8,
                ventilators_available=3,
                monitors_available=7,
                ct_available=True,
                surgical_team_available=True,
                neonatal_support_available=True,
                blood_bank_available=True,
                er_load=0.76,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=4,
                surgeons=3,
                neurosurgeons=1,
                neurologists=1,
                obstetricians=2,
                pediatricians=2,
                cardiologists=1,
                anesthetists=3,
                nurses=16,
            ),
            contact_channel="ed-korlebu@example.test",
            bed_barcodes=["KB-ICU-01", "KB-ICU-02", "KB-ER-11", "KB-ER-12", "KB-MAT-04"],
        ),
        Hospital(
            id="ridge-hospital",
            name="Greater Accra Regional Hospital",
            city="Accra",
            level="regional",
            location=Location(city="Accra", latitude=5.5608, longitude=-0.2017, address="Castle Road, Ridge"),
            capabilities=["oxygen", "obstetric", "pediatric", "neonatal_support", "emergency"],
            capacity=CapacityStatus(
                er_beds_available=5,
                icu_beds_available=1,
                maternity_beds_available=4,
                pediatric_beds_available=4,
                isolation_rooms_available=1,
                oxygen_points_available=6,
                ventilators_available=1,
                monitors_available=5,
                ct_available=False,
                surgical_team_available=True,
                neonatal_support_available=True,
                blood_bank_available=True,
                er_load=0.42,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=3,
                surgeons=1,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=3,
                pediatricians=3,
                cardiologists=0,
                anesthetists=2,
                nurses=14,
            ),
            contact_channel="ed-ridge@example.test",
            bed_barcodes=["RID-ER-01", "RID-ER-02", "RID-MAT-01", "RID-NICU-01"],
        ),
        Hospital(
            id="37-military",
            name="37 Military Hospital",
            city="Accra",
            level="specialist",
            location=Location(city="Accra", latitude=5.5904, longitude=-0.1837, address="Liberation Road"),
            capabilities=["icu", "oxygen", "ct", "trauma", "surgical_team", "cardiac", "ventilator"],
            capacity=CapacityStatus(
                er_beds_available=2,
                icu_beds_available=1,
                maternity_beds_available=1,
                pediatric_beds_available=1,
                isolation_rooms_available=0,
                oxygen_points_available=5,
                ventilators_available=2,
                monitors_available=5,
                ct_available=True,
                surgical_team_available=True,
                neonatal_support_available=False,
                blood_bank_available=True,
                er_load=0.61,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=3,
                surgeons=2,
                neurosurgeons=1,
                neurologists=0,
                obstetricians=1,
                pediatricians=1,
                cardiologists=1,
                anesthetists=2,
                nurses=12,
            ),
            contact_channel="ed-37@example.test",
            bed_barcodes=["37-ICU-01", "37-ER-01", "37-ER-02"],
        ),
        Hospital(
            id="komfo-anokye",
            name="Komfo Anokye Teaching Hospital",
            city="Kumasi",
            level="teaching",
            location=Location(city="Kumasi", latitude=6.6970, longitude=-1.6281, address="Bantama"),
            capabilities=["icu", "oxygen", "ct", "trauma", "stroke", "surgical_team", "neonatal_support", "blood_bank"],
            capacity=CapacityStatus(
                er_beds_available=4,
                icu_beds_available=2,
                maternity_beds_available=3,
                pediatric_beds_available=3,
                isolation_rooms_available=1,
                oxygen_points_available=7,
                ventilators_available=2,
                monitors_available=6,
                ct_available=True,
                surgical_team_available=True,
                neonatal_support_available=True,
                blood_bank_available=True,
                er_load=0.68,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=4,
                surgeons=3,
                neurosurgeons=1,
                neurologists=1,
                obstetricians=2,
                pediatricians=2,
                cardiologists=1,
                anesthetists=2,
                nurses=15,
            ),
            contact_channel="ed-kath@example.test",
            bed_barcodes=["KATH-ICU-01", "KATH-ICU-02", "KATH-ER-01", "KATH-MAT-02"],
        ),
        Hospital(
            id="kumasi-south",
            name="Kumasi South Hospital",
            city="Kumasi",
            level="regional",
            location=Location(city="Kumasi", latitude=6.6372, longitude=-1.5941, address="Chirapatre"),
            capabilities=["oxygen", "obstetric", "pediatric", "emergency"],
            capacity=CapacityStatus(
                er_beds_available=6,
                icu_beds_available=0,
                maternity_beds_available=5,
                pediatric_beds_available=3,
                isolation_rooms_available=1,
                oxygen_points_available=4,
                ventilators_available=0,
                monitors_available=4,
                ct_available=False,
                surgical_team_available=False,
                neonatal_support_available=True,
                blood_bank_available=False,
                er_load=0.35,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=2,
                surgeons=0,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=2,
                pediatricians=2,
                cardiologists=0,
                anesthetists=1,
                nurses=10,
            ),
            contact_channel="ed-kumasi-south@example.test",
            bed_barcodes=["KS-ER-01", "KS-MAT-01", "KS-PED-01"],
        ),
        Hospital(
            id="suntreso-hospital",
            name="Suntreso Government Hospital",
            city="Kumasi",
            level="district",
            location=Location(city="Kumasi", latitude=6.6885, longitude=-1.6595, address="Suntreso"),
            capabilities=["oxygen", "emergency", "pediatric"],
            capacity=CapacityStatus(
                er_beds_available=4,
                icu_beds_available=0,
                maternity_beds_available=1,
                pediatric_beds_available=2,
                isolation_rooms_available=0,
                oxygen_points_available=3,
                ventilators_available=0,
                monitors_available=3,
                ct_available=False,
                surgical_team_available=False,
                neonatal_support_available=False,
                blood_bank_available=False,
                er_load=0.28,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=1,
                surgeons=0,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=1,
                pediatricians=1,
                cardiologists=0,
                anesthetists=0,
                nurses=8,
            ),
            contact_channel="ed-suntreso@example.test",
            bed_barcodes=["SUN-ER-01", "SUN-ER-02"],
        ),
        Hospital(
            id="tamale-teaching",
            name="Tamale Teaching Hospital",
            city="Tamale",
            level="teaching",
            location=Location(city="Tamale", latitude=9.4052, longitude=-0.8424, address="Salaga Road"),
            capabilities=["icu", "oxygen", "ct", "trauma", "surgical_team", "neonatal_support", "blood_bank"],
            capacity=CapacityStatus(
                er_beds_available=4,
                icu_beds_available=1,
                maternity_beds_available=3,
                pediatric_beds_available=3,
                isolation_rooms_available=1,
                oxygen_points_available=5,
                ventilators_available=1,
                monitors_available=5,
                ct_available=True,
                surgical_team_available=True,
                neonatal_support_available=True,
                blood_bank_available=True,
                er_load=0.58,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=3,
                surgeons=2,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=2,
                pediatricians=2,
                cardiologists=1,
                anesthetists=2,
                nurses=13,
            ),
            contact_channel="ed-tamale-teaching@example.test",
            bed_barcodes=["TTH-ICU-01", "TTH-ER-01", "TTH-MAT-02"],
        ),
        Hospital(
            id="tamale-west",
            name="Tamale West Hospital",
            city="Tamale",
            level="regional",
            location=Location(city="Tamale", latitude=9.4210, longitude=-0.8647, address="West Hospital Road"),
            capabilities=["oxygen", "obstetric", "pediatric", "emergency"],
            capacity=CapacityStatus(
                er_beds_available=5,
                icu_beds_available=0,
                maternity_beds_available=4,
                pediatric_beds_available=3,
                isolation_rooms_available=1,
                oxygen_points_available=4,
                ventilators_available=0,
                monitors_available=4,
                ct_available=False,
                surgical_team_available=False,
                neonatal_support_available=True,
                blood_bank_available=False,
                er_load=0.31,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=2,
                surgeons=0,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=2,
                pediatricians=2,
                cardiologists=0,
                anesthetists=1,
                nurses=9,
            ),
            contact_channel="ed-tamale-west@example.test",
            bed_barcodes=["TW-ER-01", "TW-MAT-01", "TW-PED-01"],
        ),
        Hospital(
            id="tamale-central",
            name="Tamale Central Hospital",
            city="Tamale",
            level="district",
            location=Location(city="Tamale", latitude=9.4008, longitude=-0.8322, address="Central Tamale"),
            capabilities=["oxygen", "emergency"],
            capacity=CapacityStatus(
                er_beds_available=3,
                icu_beds_available=0,
                maternity_beds_available=1,
                pediatric_beds_available=1,
                isolation_rooms_available=0,
                oxygen_points_available=2,
                ventilators_available=0,
                monitors_available=2,
                ct_available=False,
                surgical_team_available=False,
                neonatal_support_available=False,
                blood_bank_available=False,
                er_load=0.25,
            ),
            specialists=SpecialistRoster(
                emergency_physicians=1,
                surgeons=0,
                neurosurgeons=0,
                neurologists=0,
                obstetricians=0,
                pediatricians=1,
                cardiologists=0,
                anesthetists=0,
                nurses=7,
            ),
            contact_channel="ed-tamale-central@example.test",
            bed_barcodes=["TC-ER-01", "TC-ER-02"],
        ),
    ]
    return {hospital.id: hospital for hospital in hospitals}


def seed_ambulances() -> dict[str, Ambulance]:
    ambulances = [
        Ambulance(
            id="amb-accra-01",
            call_sign="NAS Accra 01",
            city="Accra",
            status="available",
            location=Location(city="Accra", latitude=5.5656, longitude=-0.1969, address="National Ambulance Station, Accra"),
            crew=["EMT Adjei", "Paramedic Mensah"],
            equipment=["oxygen", "monitor", "defibrillator", "trauma_kit"],
        ),
        Ambulance(
            id="amb-accra-02",
            call_sign="NAS Accra 02",
            city="Accra",
            status="available",
            location=Location(city="Accra", latitude=5.6037, longitude=-0.1870, address="Airport Station"),
            crew=["EMT Owusu", "Paramedic Boateng"],
            equipment=["oxygen", "monitor", "obstetric_kit"],
        ),
        Ambulance(
            id="amb-kumasi-01",
            call_sign="NAS Kumasi 01",
            city="Kumasi",
            status="available",
            location=Location(city="Kumasi", latitude=6.6885, longitude=-1.6244, address="Bantama Station"),
            crew=["EMT Yeboah", "Paramedic Appiah"],
            equipment=["oxygen", "monitor", "trauma_kit"],
        ),
        Ambulance(
            id="amb-tamale-01",
            call_sign="NAS Tamale 01",
            city="Tamale",
            status="available",
            location=Location(city="Tamale", latitude=9.4075, longitude=-0.8533, address="Tamale Metro Station"),
            crew=["EMT Fuseini", "Paramedic Abubakari"],
            equipment=["oxygen", "monitor", "pediatric_kit"],
        ),
    ]
    return {ambulance.id: ambulance for ambulance in ambulances}


def seed_patient_records() -> dict[str, PatientRecord]:
    records = [
        PatientRecord(
            patient_id="FHIR-PAT-1001",
            name="Ama Serwaa",
            age=34,
            sex="female",
            allergies=["penicillin"],
            conditions=["hypertension", "pregnancy"],
            medications=["labetalol"],
            preferred_hospitals=["ridge-hospital", "korle-bu-teaching"],
            fhir_reference="Patient/FHIR-PAT-1001",
        ),
        PatientRecord(
            patient_id="FHIR-PAT-1002",
            name="Kwame Owusu",
            age=61,
            sex="male",
            allergies=[],
            conditions=["type 2 diabetes", "atrial fibrillation"],
            medications=["metformin", "apixaban"],
            preferred_hospitals=["korle-bu-teaching", "37-military"],
            fhir_reference="Patient/FHIR-PAT-1002",
        ),
        PatientRecord(
            patient_id="FHIR-PAT-2001",
            name="Amina Yakubu",
            age=7,
            sex="female",
            allergies=["sulfa"],
            conditions=["asthma"],
            medications=["salbutamol inhaler"],
            preferred_hospitals=["tamale-teaching", "tamale-west"],
            fhir_reference="Patient/FHIR-PAT-2001",
        ),
    ]
    return {record.patient_id: record for record in records}


def patient_identifier_index() -> dict[str, str]:
    return {
        "GHA-123456789-0": "FHIR-PAT-1001",
        "NHIS-AC-0001": "FHIR-PAT-1001",
        "GHA-222333444-1": "FHIR-PAT-1002",
        "NHIS-AC-0002": "FHIR-PAT-1002",
        "GHA-777888999-2": "FHIR-PAT-2001",
        "NHIS-TM-0007": "FHIR-PAT-2001",
    }

